graph LR
    Tech[Computer / Phone / Till]

    Sand -- Furnace --> Glass
    Sand -- Furnace --> Silicon

    Silicon -- Etcher --> Chips

    CrudeOil -- Refinery --> Plastic
    CrudeOil -- Refinery --> Petrol

    Glass -- Assembly --> Tech
    Plastic -- Assembly --> Tech
    Chips -- Assembly --> Tech

    Tree -- Sawmill --> Planks

    Plastic -- Assembly --> Furniture
    Planks -- Assembly --> Furniture

    IronOre -- Mine --> Iron
    Iron -- Assembly --> Sawmill
    Iron -- Assembly --> Pipe
    Pipe -- Assembly --> Refinery

    Iron -- Assembly --> Engine
    Pipe -- Assembly --> Engine

    Plastic -- Assembly --> Car
    Engine -- Assembly --> Car

    Iron -- Assembly --> Etcher
    Pipe -- Assembly --> Etcher
    Engine -- Assembly --> Etcher

    Iron -- Assembly --> AssemblyII
    Engine -- Assembly --> AssemblyII

    Planks -- Assembly --> AssemblyI

    Stone -- Mine --> StoneChunks
    StoneChunks -- StoneCutter --> StoneBricks
    StoneBricks -- Assembly --> Furnace
    StoneBricks -- StoneCutter --> StoneCutter
    StoneBricks -- StoneCutter --> Statue

    Silicon -- Furnace --> CementChunk
    Sand -- Furnace  --> CementChunk
    CementChunk -- Grinder --> Cement
    Cement --> ConcreteBlock
    StoneChunks --> ConcreteBlock



    classDef product fill:#99C794;
    class Tech,Furniture,Car,Statue,ConcreteBlock,Planks,StoneBricks product;

    classDef production fill:#C594C5;
    class AssemblyI,AssemblyII,Etcher,Refinery,Furnace,StoneCutter,Sawmill production;

    classDef raw fill:#EC5f67;
    class Stone,IronOre,Sand,Tree,CrudeOil raw;

    classDef l1 fill:#F99157;
    class Iron,StoneChunks,Silicon,Petrol,Plastic,Glass,CementChunk l1;

    classDef l2 fill:#FAC863;
    class Pipe,Chips,Engine,Cement l2;
